# Generated by Django 2.1.7 on 2019-02-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_tauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tauth',
            old_name='usename',
            new_name='username',
        ),
    ]
