# Generated by Django 2.1.7 on 2019-05-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_csp'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=100)),
                ('subject_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('present', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('branch_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('tid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
